import React, { useEffect, useRef, useState } from 'react'
import { riskLevel, fmtUSD, fmtDate, TYPOLOGY_NAMES, TYPOLOGY_DESC } from '../utils/design.js'
import NetworkGraph3D from './NetworkGraph3D.jsx'

export default function CasePanel({ patternId, detail, loading, onClose }) {
  const [tab, setTab] = useState('overview')
  const [sarCopied, setSarCopied] = useState(false)

  // Close on Escape
  useEffect(() => {
    const fn = e => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', fn)
    return () => window.removeEventListener('keydown', fn)
  }, [onClose])

  const TABS = [
    { id: 'overview',  label: 'Overview' },
    { id: 'network',   label: 'Transaction Network' },
    { id: 'checklist', label: 'Regulatory Checklist' },
    { id: 'sar',       label: 'SAR Pre-Draft' },
  ]

  const c = detail?.candidate
  const rl = c ? riskLevel(c.risk_score) : null

  const copySAR = () => {
    if (!detail?.sar_template) return
    const t = detail.sar_template
    const text = [
      'SUSPICIOUS ACTIVITY REPORT — PRE-DRAFT',
      '========================================',
      `Detection Date: ${t.detection_date}`,
      `Typology: ${t.typology}`,
      `Risk Score: ${t.risk_score?.toFixed(1)} / 100`,
      '',
      'SUBJECT ACCOUNTS',
      (t.subject_account_ids || []).join('\n'),
      '',
      'TRANSACTION SUMMARY',
      `Total transactions: ${t.transaction_count}`,
      `Flagged transactions: ${t.flagged_count}`,
      `Total volume: $${t.total_volume?.toLocaleString('en-US', { maximumFractionDigits: 0 })}`,
      `Financial institutions: ${t.banks_involved}`,
      '',
      'NARRATIVE',
      t.narrative,
      '',
      '— Generated by QLANTERN · Team 2 Quantum Pulse',
    ].join('\n')
    navigator.clipboard.writeText(text).then(() => {
      setSarCopied(true)
      setTimeout(() => setSarCopied(false), 2000)
    })
  }

  return (
    <>
      {/* Backdrop */}
      <div
        className="overlay-backdrop"
        onClick={onClose}
        style={{
          position: 'fixed', inset: 0,
          background: 'rgba(0,0,0,0.35)', zIndex: 300,
        }}
      />

      {/* Panel */}
      <div
        className="panel-slide"
        style={{
          position: 'fixed', top: 0, right: 0, bottom: 0,
          width: 680, background: '#fff',
          zIndex: 400, display: 'flex', flexDirection: 'column',
          boxShadow: '-20px 0 60px rgba(0,0,0,0.08)',
        }}
      >
        {/* Panel header */}
        <div style={{
          padding: '20px 28px', borderBottom: '1px solid #f3f4f6',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          flexShrink: 0,
        }}>
          <div>
            {loading ? (
              <div className="skeleton" style={{ height: 18, width: 200, background: '#f3f4f6', borderRadius: 4 }} />
            ) : c ? (
              <>
                <div style={{ fontSize: 16, fontWeight: 600, color: '#0a0a0a', letterSpacing: '-0.02em' }}>
                  Pattern {c.pattern_id} — {TYPOLOGY_NAMES[c.pattern_type] || c.pattern_type}
                </div>
                <div style={{ fontSize: 12, color: '#9ca3af', marginTop: 3 }}>
                  Full investigation view
                </div>
              </>
            ) : null}
          </div>
          <button
            onClick={onClose}
            style={{
              width: 32, height: 32, borderRadius: '50%',
              border: '1px solid #f3f4f6', background: '#fff',
              cursor: 'pointer', display: 'flex', alignItems: 'center',
              justifyContent: 'center', color: '#9ca3af', fontSize: 16,
            }}
          >
            ×
          </button>
        </div>

        {/* Tabs */}
        <div style={{
          display: 'flex', gap: 0, padding: '0 28px',
          borderBottom: '1px solid #f3f4f6', flexShrink: 0,
        }}>
          {TABS.map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              style={{
                padding: '12px 16px', fontSize: 13, fontWeight: 500,
                border: 'none', background: 'none', cursor: 'pointer',
                color: tab === t.id ? '#0a0a0a' : '#9ca3af',
                borderBottom: tab === t.id ? '2px solid #0a0a0a' : '2px solid transparent',
                marginBottom: -1, transition: 'color 0.1s',
              }}
            >
              {t.label}
              {t.id === 'checklist' && detail && (
                <span style={{
                  marginLeft: 6, fontSize: 11, fontWeight: 600,
                  background: detail.sar_recommended ? '#f0fdf4' : '#fef2f2',
                  color: detail.sar_recommended ? '#166534' : '#b91c1c',
                  borderRadius: 10, padding: '1px 6px',
                }}>
                  {detail.checks_passed}/6
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Panel body */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '28px' }}>
          {loading && <PanelSkeleton />}

          {!loading && detail && (
            <>
              {tab === 'overview' && <OverviewTab c={c} rl={rl} detail={detail} />}
              {tab === 'network'  && <NetworkTab c={c} network={detail.network} />}
              {tab === 'checklist' && <ChecklistTab detail={detail} />}
              {tab === 'sar'      && <SARTab detail={detail} onCopy={copySAR} copied={sarCopied} />}
            </>
          )}
        </div>
      </div>
    </>
  )
}

// ── Overview Tab ──────────────────────────────────────────────────────────────
function OverviewTab({ c, rl, detail }) {
  if (!c) return null
  return (
    <div className="fade-up">
      {/* Risk badge + title */}
      <div style={{ marginBottom: 24 }}>
        <span style={{ fontSize: 11, fontWeight: 600, background: rl.bg, color: rl.fg, borderRadius: 5, padding: '3px 9px', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
          {rl.label}
        </span>
        <div style={{ fontSize: 18, fontWeight: 600, color: '#0a0a0a', letterSpacing: '-0.03em', marginTop: 12, marginBottom: 6 }}>
          {TYPOLOGY_NAMES[c.pattern_type]} Network
        </div>
        <p style={{ fontSize: 13, color: '#6b7280', lineHeight: 1.6 }}>
          {TYPOLOGY_DESC[c.pattern_type]}
        </p>
      </div>

      {/* Key metrics */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 1, background: '#f3f4f6', borderRadius: 10, overflow: 'hidden', marginBottom: 24 }}>
        {[
          { label: 'Risk score', value: `${c.risk_score.toFixed(1)} / 100` },
          { label: 'Flagged transactions', value: `${c.laundering_edges} of ${c.region_edges}` },
          { label: 'Total volume', value: fmtUSD(c.transaction_volume) },
          { label: 'Accounts in network', value: c.region_nodes },
          { label: 'Financial institutions', value: c.unique_banks },
          { label: 'Detected', value: fmtDate(c.snapshot_time) },
        ].map(({ label, value }) => (
          <div key={label} style={{ background: '#fff', padding: '14px 16px' }}>
            <div style={{ fontSize: 15, fontWeight: 600, color: '#0a0a0a', letterSpacing: '-0.02em' }}>{value}</div>
            <div style={{ fontSize: 11, color: '#9ca3af', marginTop: 2 }}>{label}</div>
          </div>
        ))}
      </div>

      {/* Why QUBO selected */}
      {c.why_qubo_selected && (
        <div style={{ background: '#fafafa', border: '1px solid #f3f4f6', borderRadius: 10, padding: '16px 18px', marginBottom: 24 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 8 }}>
            Why QLANTERN selected this case
          </div>
          <p style={{ fontSize: 13, color: '#374151', lineHeight: 1.6 }}>{c.why_qubo_selected}</p>
        </div>
      )}

      {/* Also selected by */}
      {c.selected_by_methods && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 10 }}>
            Selected by other methods
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {c.selected_by_methods.split(';').map(m => m.trim()).filter(Boolean).map((m, i) => (
              <span key={i} style={{ fontSize: 11, background: '#f3f4f6', color: '#374151', borderRadius: 4, padding: '3px 9px', fontWeight: 500 }}>
                {m}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Account list */}
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 12 }}>
          Account identifiers ({c.n_accounts} total)
        </div>
        <div style={{ border: '1px solid #f3f4f6', borderRadius: 8, overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead>
              <tr style={{ borderBottom: '1px solid #f3f4f6' }}>
                <th style={{ padding: '8px 12px', textAlign: 'left', fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Bank</th>
                <th style={{ padding: '8px 12px', textAlign: 'left', fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Account ID</th>
                <th style={{ padding: '8px 12px', textAlign: 'left', fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Status</th>
              </tr>
            </thead>
            <tbody>
              {(c.accounts || []).slice(0, 10).map((acc, i) => {
                const parts = acc.split('::')
                return (
                  <tr key={i} style={{ borderBottom: '1px solid #fafafa' }}>
                    <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#6b7280' }}>{parts[0] || '—'}</td>
                    <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#374151' }}>{parts[1] || acc}</td>
                    <td style={{ padding: '8px 12px' }}>
                      {i < c.laundering_edges ? (
                        <span style={{ fontSize: 11, fontWeight: 600, background: '#fef2f2', color: '#b91c1c', borderRadius: 4, padding: '1px 7px' }}>Flagged</span>
                      ) : (
                        <span style={{ fontSize: 11, color: '#9ca3af' }}>Normal</span>
                      )}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
          {c.n_accounts > 10 && (
            <div style={{ padding: '10px 12px', fontSize: 11, color: '#9ca3af', borderTop: '1px solid #f3f4f6' }}>
              {c.n_accounts - 10} more accounts not shown
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Network Tab (3D) ──────────────────────────────────────────────────────────
function NetworkTab({ c, network }) {
  return (
    <NetworkGraph3D network={network} candidate={c} />
  )
}

// ── Checklist Tab ─────────────────────────────────────────────────────────────
function ChecklistTab({ detail }) {
  return (
    <div className="fade-up">
      <div style={{ marginBottom: 20 }}>
        <div style={{ fontSize: 14, fontWeight: 600, color: '#0a0a0a', marginBottom: 4 }}>
          Regulatory compliance checklist
        </div>
        <p style={{ fontSize: 12, color: '#9ca3af' }}>
          AML compliance indicators for SAR filing decision
        </p>
      </div>

      <div style={{
        background: detail.sar_recommended ? '#f0fdf4' : '#fef2f2',
        border: `1px solid ${detail.sar_recommended ? '#bbf7d0' : '#fecaca'}`,
        borderRadius: 10, padding: '14px 18px', marginBottom: 24,
        display: 'flex', alignItems: 'center', gap: 12,
      }}>
        <div style={{ fontSize: 22, fontWeight: 700, color: detail.sar_recommended ? '#166534' : '#b91c1c' }}>
          {detail.checks_passed}/6
        </div>
        <div>
          <div style={{ fontSize: 13, fontWeight: 600, color: detail.sar_recommended ? '#166534' : '#b91c1c' }}>
            {detail.sar_recommended ? 'SAR filing recommended' : 'Insufficient indicators for SAR'}
          </div>
          <div style={{ fontSize: 12, color: '#6b7280', marginTop: 1 }}>
            {detail.checks_passed} of 6 compliance indicators triggered
          </div>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {(detail.checklist || []).map((item, i) => (
          <div key={i} style={{
            border: '1px solid #f3f4f6', borderRadius: 9,
            padding: '14px 16px', display: 'flex', gap: 14, alignItems: 'flex-start',
          }}>
            <div style={{
              width: 24, height: 24, borderRadius: '50%', flexShrink: 0,
              background: item.status ? '#f0fdf4' : '#fef2f2',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 13, fontWeight: 700,
              color: item.status ? '#166534' : '#b91c1c',
              marginTop: 1,
            }}>
              {item.status ? '✓' : '✗'}
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 500, color: '#0a0a0a', marginBottom: 3 }}>
                {item.item}
              </div>
              <div style={{ fontSize: 12, color: '#6b7280' }}>{item.detail}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── SAR Tab ───────────────────────────────────────────────────────────────────
function SARTab({ detail, onCopy, copied }) {
  if (!detail?.sar_template) return null
  const t = detail.sar_template

  return (
    <div className="fade-up">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 }}>
        <div>
          <div style={{ fontSize: 14, fontWeight: 600, color: '#0a0a0a', marginBottom: 4 }}>
            Suspicious Activity Report — Pre-Draft
          </div>
          <p style={{ fontSize: 12, color: '#9ca3af' }}>
            Auto-populated from investigation data. Review before filing.
          </p>
        </div>
        <button
          onClick={onCopy}
          style={{
            background: copied ? '#166534' : '#0a0a0a', color: '#fff',
            border: 'none', borderRadius: 7, padding: '8px 16px',
            fontSize: 12, fontWeight: 500, cursor: 'pointer',
            transition: 'background 0.2s',
          }}
        >
          {copied ? 'Copied!' : 'Copy to clipboard'}
        </button>
      </div>

      <div style={{ border: '1px solid #f3f4f6', borderRadius: 10, overflow: 'hidden' }}>
        <div style={{ padding: '14px 18px', borderBottom: '1px solid #f3f4f6', background: '#fafafa' }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
            Report header
          </div>
        </div>
        {[
          ['Detection date', fmtDate(t.detection_date)],
          ['Suspected typology', t.typology],
          ['Risk score', `${t.risk_score?.toFixed(1)} / 100`],
          ['Total transactions', t.transaction_count],
          ['Flagged transactions', t.flagged_count],
          ['Total volume', fmtUSD(t.total_volume)],
          ['Financial institutions', t.banks_involved],
        ].map(([label, value]) => (
          <div key={label} style={{ display: 'flex', padding: '11px 18px', borderBottom: '1px solid #fafafa' }}>
            <div style={{ width: 180, fontSize: 12, color: '#9ca3af', flexShrink: 0 }}>{label}</div>
            <div style={{ fontSize: 12, fontWeight: 500, color: '#0a0a0a' }}>{value}</div>
          </div>
        ))}

        <div style={{ padding: '14px 18px', borderBottom: '1px solid #f3f4f6', background: '#fafafa', marginTop: 8 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
            Subject accounts
          </div>
        </div>
        <div style={{ padding: '12px 18px', borderBottom: '1px solid #f3f4f6' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {(t.subject_account_ids || []).map((acc, i) => (
              <span key={i} style={{ fontFamily: 'monospace', fontSize: 11, background: '#f3f4f6', padding: '3px 8px', borderRadius: 4, color: '#374151' }}>
                {acc}
              </span>
            ))}
          </div>
        </div>

        <div style={{ padding: '14px 18px', borderBottom: '1px solid #f3f4f6', background: '#fafafa' }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
            Narrative
          </div>
        </div>
        <div style={{ padding: '14px 18px' }}>
          <p style={{ fontSize: 13, color: '#374151', lineHeight: 1.7 }}>{t.narrative}</p>
        </div>
      </div>

      <div style={{ marginTop: 16, padding: '12px 16px', background: '#fefce8', border: '1px solid #fef08a', borderRadius: 8 }}>
        <p style={{ fontSize: 12, color: '#854d0e', lineHeight: 1.6 }}>
          <strong>Note:</strong> This pre-draft is auto-generated from QLANTERN analysis. 
          All fields must be verified by a qualified compliance officer before filing. 
          This does not constitute legal or regulatory advice.
        </p>
      </div>
    </div>
  )
}

// ── Skeleton ──────────────────────────────────────────────────────────────────
function PanelSkeleton() {
  return (
    <div>
      {[200, 120, 80, 160, 100].map((w, i) => (
        <div key={i} className="skeleton" style={{
          height: 14, width: `${w}px`, background: '#f3f4f6',
          borderRadius: 4, marginBottom: 16,
        }} />
      ))}
    </div>
  )
}
